### ISSUE TITLE
Zootaxz Mod Frage

### ISSUE THREAD

**Issue by Alheimerjung** [Alheimerjung/Textures-Scrumble#1]
@Zootaxz ich habe mal eine Frage könntest du mir bei einem kleinen Mod Problem helfen ?

**Comment by Zootaxz** [comment]
Vielleicht.. kanns versuchen :D

**Comment by Alheimerjung** [comment]
Dürfte ein leichtes für dich sein. Ich möchte einen Block(Maschine) also praktisch wie ein Macerator oder ein Pulvireiser nur mit anderer Funktion hinzufügen. Den Anfang habe ich schon gemacht und habe den Block und die Tile erstellt.

Code: https://github.com/ForestDay/Forest-Day/tree/Dev
